CREATE TABLE ZOO_APPLICANTS
  (
    ZOOKEEPER_ID   NUMBER,
    ZOOKEEPER_NAME CHAR(50 BYTE),
    TELEPHONE      CHAR(15 BYTE),
    EMAIL          CHAR(50 BYTE),
    BIRTHDATE      CHAR(10 BYTE),
    AGE            CHAR(3 BYTE),
    GENDER         CHAR(6 BYTE),
    COMMENTS       CHAR(200 BYTE),
    ANIMALS        CHAR(200 BYTE),
    PRIMARY KEY (ZOOKEEPER_ID) 
  )